engines:
  tslint:
    enabled: true
    config: tslint.json
  eslint:
    enabled: false
  csslint:
    enabled: false
  rubocop:
    enabled: false
ratings:
  paths:
  - "src/**/*"
  - "!src/**/*.test.ts"
  - "**.md"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 700
  method-complexity:
    config:
      threshold: 16
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 80
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 8
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_patterns:
- src/**/*.test.ts
- dist/**/*
- coverage/**/*
- data/**/*
